<?php

define('BASE_ROOT', dirname(__FILE__, 2) . DIRECTORY_SEPARATOR);
define('BASE_APP', BASE_ROOT . 'src' . DIRECTORY_SEPARATOR);
define('BASE_VIEW', BASE_ROOT . 'views' . DIRECTORY_SEPARATOR);
define('BASE_ROUTER', BASE_ROOT . 'routes' . DIRECTORY_SEPARATOR);
define('BASE_PUBLIC', BASE_ROOT . 'public' . DIRECTORY_SEPARATOR);
define('BASE_CONFIG', BASE_ROOT . 'config' . DIRECTORY_SEPARATOR);
define('SYSTEM_NAME', BASE_ROOT . 'BaseBuild' . DIRECTORY_SEPARATOR);